### ISSUE TITLE
the last nexcloud cliend from f-droid crashes

### ISSUE THREAD

**Issue by 532910** [kd2org/karadav#39]
1. start karadav in docker: https://f-droid.org/en/packages/com.nextcloud.client/
2. Install https://f-droid.org/en/packages/com.nextcloud.client/

### Cause of error
```java
Exception in thread "Thread-7" java.lang.NumberFormatException: For input string: "eJwrTi1K"
    at java.lang.Long.parseLong(Long.java:736)
    at java.lang.Long.parseLong(Long.java:861)
    at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:606)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:461)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFolder(FileDataStorageManager.java:478)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:392)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:538)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```
### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2120`
* Id: `TQ2A.230505.002`
* Product: `OnePlus9Pro`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `121`

**Comment by 532910** [comment]
nextcloud-dev crashes the same way

**Comment by bohwaz** [comment]
Damn this software is extremly brittle, anything unexpected and it crashes. This sucks.

They just decided that file IDs should be an integer. Unfortunately this change means that KaraDAV can no longer be compatible with NextCloud as we don't store File IDs (no file metadata is stored in database), so it's a hash of the file path.

I'm trying to find a way to get around this limitation.

**Comment by bohwaz** [comment]
Source change: https://github.com/nextcloud/android/commit/b78e991d54ad9f4b9e5b7474c601e2c8b716ed30

**Comment by bohwaz** [comment]
PR: https://github.com/nextcloud/android/pull/8643

**Comment by bohwaz** [comment]
Related NextCloud Android issue: https://github.com/nextcloud/android/issues/11718

**Comment by bohwaz** [comment]
I changed the fileID to be a random integer, it does work for me. Please update to last release, and report back if it doesn't work for you.
